---
name: dart

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: "16.x"


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.0

      - name: Analyze Flutter
        run:  flutter analyze

      - name: Install dependencies
        run: dart pub get

      - name: Analyze Dart
        run:  dart analyze



      - name: Build the AAB
        env:
          APP_VERSION_CODE: 1.0.0+1
        run: flutter build appbundle

      - name: Uploading artifacts android
        uses: actions/upload-artifact@v3
        with:
         name: app-release-build-artifact
         path:  build/app/outputs/bundle/release/app-release.aab

      - name: Install fastlane
        run: sudo gem install fastlane

      - name: Run Fastlane
        uses: maierj/fastlane-action@v3.0.0
        env:
            PACKAGE_NAME: com.example.aaplication01statemanagment
        with:
              lane: deploy
              subdirectory: android

