---
name: dart

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1






      - name: Analyze project source
        run: dart analyze


      - name: Run tests
        run: dart test